name: Release Tag To Hex.pm

on:
  push:
    tags: [ "v*" ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-beam@61e01a43a562a89bfc54c7f9a378ff67b03e4a21 # v1.16.0
      with:
        elixir-version: '1.15.2'
        otp-version: '26.0'
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: mix test test --cover
    - name: Run example phoenix project tests
      run: |
       cd examples/phoenix_project
       mix deps.get
       mix test
    - name: Run example mix project tests
      run: |
        cd examples/mix_project
        mix deps.get
        mix test
    - name: Verify version
      run: |
        mix run -e "if(Testcontainers.Constants.library_version() == Mix.Project.config()[:version], do: IO.puts("OK"), else: System.halt(\"version mismatch\"))"
    - name: Publish to Hex.pm
      env:
        HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
      run: mix hex.publish --yes